FROM python:3.11-slim

# Application will be present in /workspace directory
WORKDIR /workspace/webcat

RUN python3 -m pip install --upgrade pip
RUN pip install flask
RUN pip install flask-restful
RUN pip install flask-cors
RUN pip install flask-sqlalchemy
RUN pip install python-dotenv
RUN pip install urlextract
RUN pip install psycopg2-binary
RUN pip install beautifulsoup4
RUN pip install joblib
RUN pip install transformers
RUN pip install nltk
RUN pip3 install --default-timeout=100 torch
RUN pip install datasets
RUN pip install openai==0.27.0
RUN pip install sentencepiece
RUN pip install protobuf==3.20.0
RUN pip install datefinder
RUN pip install debugpy
RUN pip install lxml

