drugs_article = "Thailand's health minister on Wednesday discouraged tourists from visiting the country only to smoke weed, just two months after new laws were passed that have largely decriminalized the drug."

firearms_article = "Washington Commanders rookie running back Brian Robinson Jr. says his surgery went well after he was shot Sunday in Washington, DC, in what police say may have been an attempted robbery or carjacking."

crime_article = "Law enforcement officials believe the body found in a submerged vehicle Sunday is more than likely that of Kiely Rodni, the missing 16-year-old last seen almost three weeks ago at a campground party in Northern California, authorities said Monday."

crypto_article = "After clearing the USD 20,000 resistance zone, BTC is currently (11:36 UTC) trading near USD 20,470 and it might attempt a clear move above the USD 20,500 zone. If the bulls remain in action, the price might also test the USD 21,200 resistance. BTC is up 3% in a day and down 4% in a week. Similarly, most major altcoins are also moving higher. ETH gained pace and might test the USD 1,600 resistance. XRP is still well below the USD 0.35 resistance. ADA surpassed the USD 0.45 resistance zone."

other_article = "We introduce a new language representation model called BERT, which stands for Bidirectional Encoder Representations from Transformers. Unlike recent language representation models, BERT is designed to pre-train deep bidirectional representations from unlabeled text by jointly conditioning on both left and right context in all layers. As a result, the pre-trained BERT model can be fine-tuned with just one additional output layer to create state-of-the-art models for a wide range of tasks, such as question answering and language inference, without substantial task-specific architecture modifications."

animals_article = "Three living species are currently recognised: the African bush elephant, the African forest elephant, and the Asian elephant. They are the only surviving members of the family Elephantidae and the order Proboscidea. The order was formerly much more diverse during the Pleistocene, but most species became extinct during the Late Pleistocene epoch. Distinctive features of elephants include a long proboscis called a trunk, tusks, large ear flaps, pillar-like legs, and tough but sensitive skin. The trunk is used for breathing, bringing food and water to the mouth, and grasping objects. Tusks, which are derived from the incisor teeth, serve both as weapons and as tools for moving objects and digging. The large ear flaps assist in maintaining a constant body temperature as well as in communication. African elephants have larger ears and concave backs, whereas Asian elephants have smaller ears, and convex or level backs."