"""Migration initialization

Revision ID: ccb0d45a1fd6
Revises: 
Create Date: 2023-04-19 08:24:05.881267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb0d45a1fd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('element_types', sa.Column('tag', sa.String(length=100), nullable=True))
    op.add_column('element_types', sa.Column('analysis_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('element_types', 'analysis_flag')
    op.drop_column('element_types', 'tag')
    # ### end Alembic commands ###
