# get node image
FROM node:18.15

# Application will be present in /workspace directory
WORKDIR /workspace
COPY . .

# install dependencies
RUN npm install
EXPOSE 3000

# start application
CMD ["npm", "start"]

